---
- name: MariaDB
  hosts: dbSchoolDylan
  become: yes
  become_method: sudo
  become_user: root
  remote_user: dylanbackes
  gather_facts: true
  vars:
    mysql_root_password: "dylanbackes"

  tasks:
    - name: Update the package index
      apt:
        update_cache: yes

    - name: Install MariaDB server
      apt:
        name: mariadb-server
        state: latest

    - name: Install Pyuthon MySQL client
      apt:
        name: python3-mysqldb
        state: latest

    - name: Start and Enable the MariaDB service
      systemd:
        name: mariadb
        state: started
        enabled: yes
